# ref: https://www.youtube.com/watch?v=gEceSAJI_3s
  # ref: https://gist.github.com/erikyuzwa/7411752ddcb95b09434aa88f38d91630

  version: "3.8"

services:

  wordpress-db:
    # mariadb image which supports both amd64 & arm64 architecture
    # image: mariadb:10.6.4-focal
    image: application-wp-db-v1
    container_name: application-wp
    build:
      context: .
      dockerfile: ubuntu-container-mariadb-build.dockerfile
    ports:
      - 3306:3306
    env_file: .env.wp
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wordpress-network
    deploy:
      resources:
        limits:
          memory: 2048m
    restart: unless-stopped

  wordpress-phpmyadmin:
    depends_on:
      - wordpress-db
    # image: phpmyadmin/phpmyadmin
    image: application-wp-phpmyadmin-v1
    container_name: application-phpmyadmin
    build:
      context: .
      dockerfile: ubuntu-container-phpmyadmin-build.dockerfile
    ports:
      - 8081:80
    env_file: .env.wp
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - wordpress-network
    restart: unless-stopped

  wordpress:
    depends_on:
      - wordpress-db
    # image: wordpress:6.2.2-apache
    image: application-wp-v1
    container_name: application-phpmyadmin
    build:
      context: .
      dockerfile: ubuntu-container-build.dockerfile
    ports:
      - 8080:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306 # use the same name as database service
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./:/var/www/html/
    networks:
      - wordpress-network
    restart: unless-stopped

volumes:
  db-data:

networks:
  wordpress-network:
    driver: bridge 
    